# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Minecraft 版本
minecraft_version=26.1.2

# Fabric Loader 版本
loader_version=0.19.3

# bro刚刚才发现自己没写Loom版本
loom_version=1.17.17

# Fabric API 版本
fabric_api_version=0.155.2+26.1.2

# Melody 版本（来自 Modrinth）
melody_version=1.0.16-26.1.1

# 模组信息
mod_version=1.0.0
maven_group=com.fsaobdriiucmapi.setthebackgroundmusic
archives_base_name=setthebackgroundmusic